CREATE TABLE routes (`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,path VARCHAR(255) NOT NULL,route VARCHAR(255) NOT NULL,module VARCHAR(255) );
CREATE TABLE modules (`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255) NOT NULL,author VARCHAR(255) NOT NULL,path VARCHAR(255) NOT NULL);
